from typing import Any
from typing import Callable

def on(event_id: str, callback: Callable[..., Any]) -> None: ...
def on_all(callback: Callable[..., Any]) -> None: ...
def reset() -> None: ...
def has_listeners(event_id: str) -> bool: ...
def remove(event_id: str, callback: Callable[..., Any]) -> None: ...
def dispatch(event_id: str, args: tuple[Any, ...]) -> None: ...
def dispatch_with_results(event_id: str, args: tuple[Any, ...]) -> tuple[list[Any], list[Exception]]: ...
