from typing import Any
from typing import Optional

_CURRENT_CONTEXT: Optional[Any]

def context_with_data(identifier: str, parent: Optional[Any] = None, **kwargs: Any) -> Any: ...
def get_item(data_key: str, span: Optional[Any] = None) -> Optional[Any]: ...
def get_items(data_keys: list[str], span: Optional[Any] = None) -> Optional[Any]: ...
def set_safe(data_key: str, data_value: Any) -> None: ...
def set_item(data_key: str, data_value: Any, span: Optional[Any] = None) -> None: ...
def set_items(keys_values: dict, span: Optional[Any] = None) -> None: ...
