from typing import Any
from typing import Callable

class EventHub:
    def has_listeners(self, event_id: str) -> bool: ...
    def on(self, event_id: str, callback: Callable) -> None: ...
    def reset(self) -> None: ...
    def dispatch(self, event_id, arg: Any, *other_args: Any) -> tuple[list, list]: ...

def has_listeners(event_id: str) -> bool: ...
def on(event_id: str, callback: Callable) -> None: ...
def reset_listeners() -> None: ...
def dispatch(event_id: str, args: Any, *other_args: Any) -> tuple[list, list]: ...
